### ISSUE TITLE
still not working

### ISSUE THREAD

**Issue by Nevu** [DeutschMark/Show-Distance-And-Angle-Of-Nodes#1]
hello,

I used show-distance-and-angle-of-nodes,
but nothing seems happen.

You other plugins work very well. Great

**Comment by DeutschMark** [comment]
Can you please specify a bit? Does it even appear in the Glyphs’ View Menu? If so, which version of Glyphs are you using?

**Comment by Nevu** [comment]
This is fixed.
I had to download the latest Version again, because my Glyphs was buggy,
so it could make an Update.

Thank you
g O

**Comment by DeutschMark** [comment]
Nice to hear that. You’re welcome. Please let me know if you find any bugs.
