### ISSUE TITLE
Input of Values

### ISSUE THREAD

**Issue by Nevu** [DeutschMark/Show-Distance-And-Angle-Of-Nodes#4]
Hi again,

I had another idea to improve this plugin. 
First the reason for that ( because maybe there is an alternativ workflow): 
For now I have to look for the values ... change the stem-width ... look for the values .. and so on.

That is a bit awkward. Now:
It could be useful to have a input-field for changing the values in the displayed box. See Image.
As reference there could be the module next to font-info (I dont know how named ...).

What do you think?

Thx

<img width="615" alt="input" src="https://cloud.githubusercontent.com/assets/2456068/11456294/4b402c7c-9685-11e5-8a9b-d7db67f9909b.png">

**Comment by DeutschMark** [comment]
Hi, thanks for asking. Do you know that you can edit the numeric values below the arrow? In this case the 0 and the 170 as well as the y and y coordinates? You can tab and shift-tab to cycle through the input fields. That way you can have 2 points selected, see the distance and angle and resize the bounding box of the selection in one go. Would that help?

**Comment by Nevu** [comment]
Yes, I recognized that I can do it while make this Issue :). But Could also be nice to have an Input directly in with the Plugin. Thx

**Comment by DeutschMark** [comment]
I am afraid that this is not possible. The structure of a reporter Plugin is made to display things only, not to take and cope with direct user input.

**Comment by Nevu** [comment]
ok :) - Never want to much. But thanks for the input

**Comment by DeutschMark** [comment]
Thank you too for your thoughts. It always helps to improve things.
